# Generated by Django 5.1.5 on 2025-01-27 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_region', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('flat_house_building', models.CharField(max_length=255)),
                ('area_street_sector_village', models.CharField(max_length=255)),
                ('landmarks', models.CharField(blank=True, max_length=255, null=True)),
                ('town_city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimensions', models.CharField(max_length=50)),
                ('package_type', models.CharField(max_length=100)),
                ('time_slot', models.CharField(choices=[('Morning', 'Morning (8 AM - 12 PM)'), ('Afternoon', 'Afternoon (12 PM - 4 PM)'), ('Evening', 'Evening (4 PM - 8 PM)')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('online_payment', 'Online Payment'), ('wallet_balance', 'Wallet Balance'), ('cod', 'Cash on Delivery')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiverDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_address', to='createshipment.address')),
            ],
        ),
        migrations.CreateModel(
            name='SenderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender_address', to='createshipment.address')),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Picked Up', 'Picked Up'), ('In Transit', 'In Transit'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Booked', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_package', to='createshipment.packagedetails')),
                ('payment_option', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_payment', to='createshipment.paymentoptions')),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_receiver', to='createshipment.receiverdetails')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_sender', to='createshipment.senderdetails')),
            ],
        ),
    ]
