# Generated by Django 5.1.5 on 2025-02-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("createshipment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcel",
            name="awb_number",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
